withcatai/node-llama-cpp

src/LlamaChatSession.ts, src/cli/commands/ChatCommand.ts
Enable the model to output emoji with the default chat session
=> feat(model): support emoji

README.md, llama/addon.cpp, src/cli/commands/ChatCommand.ts, src/llamaEvaluator/LlamaChatSession.ts, src/llamaEvaluator/LlamaContext.ts, src/llamaEvaluator/LlamaModel.ts, src/utils/getBin.ts
Added support for some llama.cpp params on `LlamaModel`
=> feat: add support for some llama.cpp params on `LlamaModel`

llama/addon.cpp, src/llamaEvaluator/LlamaModel.ts
Renamed `gpuCores` param to `gpuLayers` to match llama.cpp
=> fix: rename a param to match llama.cpp

src/cli/commands/BuildCommand.ts, src/cli/commands/DownloadCommand.ts, src/llamaEvaluator/LlamaGrammar.ts, src/utils/compileLLamaCpp.ts, src/utils/getBin.ts, src/utils/getGrammarsFolder.ts
* Improved error message when `llama.cpp` source is not downloaded
* Typo fixes
* Replaced `fs.exists` with `fs.pathExists`
=> feat: improve error message when `llama.cpp` source is not downloaded

package.json
This fixes #30 
The issue is specific to Next.js (or any project that use Webpack, I think), where `default` export must be specified last in package.json. The fix simply moves it to the last.
=> fix: move default to the last in package.json

src/llamaEvaluator/LlamaChatSession.ts, src/llamaEvaluator/LlamaContext.ts
* fix: detect stop words that don't start with the token string
* fix: handle stop words remainder properly in a chat session
* feat: support decoding a token array instead of only a `Uint32Array`
=> fix: handle stop words remainder properly in a chat session

README.md, llama/addon.cpp, src/cli/commands/ChatCommand.ts, src/llamaEvaluator/LlamaModel.ts, src/utils/getBin.ts
Support setting `threads` count for a model
=> feat: `threads` count setting on a model

.config/typedoc.css, README.md, package.json
fix: load image urls properly also outside GitHub
=> fix: load image urls properly also outside GitHub

.github/workflows/build.yml, llama/CMakeLists.txt, src/utils/getBin.ts
The current compilation flow produces a binary that uses [N-API](https://nodejs.org/api/n-api.html#n_api_node_api) properly and thus is [ABI-Stable](https://nodejs.org/en/docs/guides/abi-stability), meaning that the binary is compatible with the node.js version it was compiled for (v18) and all subsequent versions.
This means that we only need to compile one binary for each platform and architecture.
This PR makes the result npm module much smaller in size and ensures compatibility with all future node.js versions in terms of binary compatibility.
=> feat: only build one binary for all node versions

README.md, src/ChatPromptWrapper.ts, src/chatWrappers/ChatMLPromptWrapper.ts, src/chatWrappers/GeneralChatPromptWrapper.ts, src/chatWrappers/LlamaChatPromptWrapper.ts, src/chatWrappers/generateContextTextFromConversationHistory.ts, src/index.ts, src/llamaEvaluator/LlamaChatSession.ts, src/llamaEvaluator/LlamaContext.ts, src/types.ts
* feat: load conversation history into a `LlamaChatSession`
Fixes #39
=> feat: load conversation history into a `LlamaChatSession`

src/utils/getBin.ts
* feat: fall back to build from source if prebuilt binary loading fails
=> feat: fall back to build from source if prebuilt binary loading fails

src/utils/compileLLamaCpp.ts
fix: make disabling metal on build work
=> fix: make disabling metal on build work

.github/workflows/build.yml, .gitignore, src/cli/commands/DownloadCommand.ts, src/config.ts, src/utils/cloneLlamaCppRepo.ts, src/utils/gitReleaseBundles.ts
Add a git bundle of the current release of `llama.cpp` to include the source as part of the package
=> feat: git release bundle

.github/workflows/build.yml, src/cli/commands/DownloadCommand.ts, src/utils/cloneLlamaCppRepo.ts, src/utils/gitReleaseBundles.ts
Fix a problem where the build fails when the repo is cloned from a local git bundle
=> fix: git bundle info for build

src/chatWrappers/GeneralChatPromptWrapper.ts, test/standalone/chatWrappers/ChatMLChatPromptWrapper.test.ts, test/standalone/chatWrappers/FalconChatPromptWrapper.test.ts, test/standalone/chatWrappers/GeneralChatPromptWrapper.test.ts, test/standalone/chatWrappers/LlamaChatPromptWrapper.test.ts
* fix: `GeneralChatPromptWrapper` output
* test: add tests to chat prompt wrappers
=> fix: `GeneralChatPromptWrapper` output

.gitignore, src/cli/commands/BuildCommand.ts, src/cli/commands/ClearCommand.ts, src/cli/commands/DownloadCommand.ts, src/commands.ts, src/config.ts, src/index.ts, src/utils/cloneLlamaCppRepo.ts, src/utils/getBuildDefaults.ts, src/utils/getReleaseInfo.ts
* feat: export `llama.cpp` release info
* feat: make it easier to use imported `build` and `download` commands from other libraries
=> feat: export `llama.cpp` release info

llama/addon.cpp, src/llamaEvaluator/LlamaContext.ts, src/llamaEvaluator/LlamaModel.ts, src/utils/compileLLamaCpp.ts, src/utils/getBin.ts
* fix: adapt to breaking changes of `llama.cpp`
* fix: fix the `The file “ggml-metal.metal” couldn’t be opened` error
Fixes #116
=> fix: adapt to breaking changes of `llama.cpp`

docs/guide/chat-session.md
Perharps some new kind of bugs generated by a too pro-efficient code assistant that insert that lib as soon as 'context' has been typed ;-)
Fixes #130
=> docs: fix code example

.releaserc.ts, llama/addon.cpp, src/chatWrappers/resolveChatWrapperBasedOnModel.ts, src/index.ts, src/llamaEvaluator/LlamaContext/LlamaContext.ts, src/llamaEvaluator/LlamaContext/types.ts, src/llamaEvaluator/LlamaEmbeddingContext.ts, src/utils/getBin.ts, test/modelDependent/functionary/embedding.test.ts, test/standalone/parseModelFileName.test.ts
* feat: get embedding for text
* feat(minor): improve `resolveChatWrapperBasedOnModel` logic
* style: improve GitHub release notes formatting
Resolves #123
```typescript
import {fileURLToPath} from "url";
import path from "path";
import {LlamaModel, LlamaEmbeddingContext} from "node-llama-cpp";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const model = new LlamaModel({
modelPath: path.join(__dirname, "models", "functionary-small-v2.2.q4_0.gguf")
});
const embeddingContext = new LlamaEmbeddingContext({
model,
contextSize: Math.min(4096, model.trainContextSize)
});
const text = "Hello world";
const embedding = await embeddingContext.getEmbeddingFor(text);
console.log(text, embedding.vector);
```
=> feat: get embedding for text

llama/addon.cpp
* fix: adapt to breaking `llama.cpp` changes
=> fix: adapt to breaking `llama.cpp` changes

llama/addon.cpp, src/chatWrappers/utils/resolveChatWrapper.ts, test/standalone/parseModelFileName.test.ts
* fix: fallback to general chat wrapper
* fix: adapt to `llama.cpp` changes
=> fix: fallback to general chat wrapper

.github/ISSUE_TEMPLATE/bug-report.yml, src/cli/commands/inspect/commands/InspectGpuCommand.ts
* feat(`inspect gpu` command): print env info
=> feat(`inspect gpu` command): print env info

.github/workflows/build.yml, templates/electron-typescript-react/package.json
=> fix: Electron example build

.github/workflows/build.yml, src/bindings/Llama.ts, src/bindings/utils/MemoryOrchestrator.ts, src/cli/commands/ChatCommand.ts, src/cli/commands/CompleteCommand.ts, src/cli/commands/DebugCommand.ts, src/cli/commands/InfillCommand.ts, src/cli/commands/inspect/commands/InspectGpuCommand.ts, src/cli/commands/inspect/commands/InspectMeasureCommand.ts, src/cli/utils/interactivelyAskForModel.ts, src/cli/utils/printCommonInfoLines.ts, src/evaluator/LlamaContext/LlamaContext.ts, src/evaluator/LlamaModel/LlamaModel.ts, src/gguf/insights/GgufInsightsConfigurationResolver.ts, src/gguf/insights/utils/resolveContextContextSizeOption.ts, src/gguf/insights/utils/resolveModelGpuLayersOption.ts, templates/electron-typescript-react/electron-builder.ts, test/modelDependent/functionary/functionaryModelGpuLayersOptions.test.ts, test/modelDependent/functionary/gguf/ggufInsights.test.ts, test/modelDependent/stableCode/stableCodeModelGpuLayersOptions.test.ts
* fix: make GPU info getters async
* fix: Electron example build
=> fix: async gpu info getters

templates/electron-typescript-react/electron-builder.ts, templates/electron-typescript-react/electron/rpc/llmRpc.ts, templates/electron-typescript-react/package.json, templates/electron-typescript-react/src/App/App.tsx, templates/electron-typescript-react/src/App/components/ChatHistory/ChatHistory.css, templates/electron-typescript-react/src/App/components/ChatHistory/ChatHistory.tsx, templates/electron-typescript-react/src/App/components/InputRow/InputRow.tsx, templates/electron-typescript-react/src/App/components/MarkdownContent/MarkdownContent.css, templates/electron-typescript-react/src/App/components/MarkdownContent/MarkdownContent.tsx, templates/electron-typescript-react/src/index.css
* feat: render markdown in the Electron example
* fix: only build practical targets by default in the Electron example
=> feat: render markdown in the Electron example

src/bindings/getLlama.ts, src/bindings/utils/compileLLamaCpp.ts
* fix: Windows and CUDA bindings
=> fix: Windows and CUDA bindings

llama/addon.cpp, src/bindings/AddonTypes.ts, src/bindings/Llama.ts, src/bindings/getLlama.ts, src/bindings/types.ts, src/bindings/utils/getGpuTypesToUseForOption.ts, src/cli/commands/ChatCommand.ts, src/cli/commands/CompleteCommand.ts, src/cli/commands/InfillCommand.ts, src/cli/commands/inspect/commands/InspectMeasureCommand.ts, src/cli/utils/printCommonInfoLines.ts, src/evaluator/LlamaContext/LlamaContext.ts, src/evaluator/LlamaContext/types.ts, src/evaluator/LlamaModel/LlamaModel.ts, src/gguf/insights/GgufInsights.ts, src/gguf/insights/GgufInsightsConfigurationResolver.ts, src/gguf/insights/utils/resolveContextContextSizeOption.ts, src/gguf/insights/utils/resolveModelGpuLayersOption.ts, src/gguf/types/GgufMetadataTypes.ts, src/index.ts
* feat: flash attention
* feat: exclude GPU types from `gpu: "auto"`
=> feat: flash attention

llama/addon.cpp
* fix: adapt to `llama.cpp` breaking changes
=> fix: adapt to `llama.cpp` breaking changes

llama/CMakeLists.txt, src/utils/compileLLamaCpp.ts
=> fix: prebuilt binaries

src/evaluator/LlamaChat/LlamaChat.ts, src/evaluator/LlamaCompletion.ts
* fix: more cases of unknown characters in generation streaming
Fixes #284
=> fix: more cases of unknown characters in generation streaming

.github/workflows/build.yml
* fix: revert to the latest stable Metal `llama.cpp` release to avoid a consistent crash
=> fix: revert to the latest stable Metal `llama.cpp` release

llama/addon.cpp
* fix: bump `llama.cpp` release used in prebuilt binaries
=> fix: bump `llama.cpp` release used in prebuilt binaries

templates/electron-typescript-react/package.json
* fix: revert `electron-builder` version used in Electron template
There's an issue with Electron Builder `>=25.0.1` where building an app produces an asar archive with a `node_modules` tree that uses wrong module versions, which causes the packaged app to behave differently than it does on dev mode, and very frequently crash or not load at all.
I'm downgrading the version of `electron-builder` used in the template electron app until this is fixed.
=> fix: revert `electron-builder` version used in Electron template

.github/workflows/build.yml, .releaserc.ts
* build: fix release job
There's an issue where if there's an environment variable with a value that's too long, calling any `npx` command fails.
=> build: fix release job

templates/node-typescript/src/index.ts
=> fix(node template): bug

docs/guide/downloading-models.md, src/bindings/Llama.ts, src/index.ts, src/utils/getLlamaClasses.ts
* feat(minor): reference common classes on the Llama instance - this is useful for libraries that use `node-llama-cpp`
=> feat(minor): reference common classes on the `Llama` instance

.github/workflows/build.yml, llama/addon/AddonContext.cpp, llama/addon/AddonModel.cpp, llama/addon/AddonModel.h, src/bindings/AddonTypes.ts, src/bindings/types.ts, src/evaluator/LlamaCompletion.ts, src/evaluator/LlamaEmbeddingContext.ts, src/evaluator/LlamaModel/LlamaModel.ts, src/gguf/insights/GgufInsights.ts, src/gguf/types/GgufMetadataTypes.ts, src/utils/tokenizeInput.ts, src/utils/tokenizerUtils.ts, test/modelDependent/llama3/functions.test.ts, test/modelDependent/nomicEmbedText/embedding.test.ts, test/modelDependent/stableCode/asyncContextLoad.test.ts, test/modelDependent/stableCode/asyncModelLoad.test.ts, test/utils/modelFiles.ts
* fix: align embedding input with WPM vocabulary type models
Fixes #391
=> fix: align embedding input with WPM vocabulary type models

package-lock.json, package.json, src/evaluator/LlamaRankingContext.ts, test/modelDependent/bgeReranker/rank.test.ts
* fix: reranking probabilities
=> fix: reranking probabilities

docs/blog/v3.6-deepseek-r1.md, src/evaluator/LlamaChatSession/utils/LlamaChatSessionPromptCompletionEngine.ts, templates/electron-typescript-react/src/App/components/ChatHistory/components/ModelResponseThought/ModelResponseThought.css, templates/electron-typescript-react/src/App/components/ChatHistory/components/ModelResponseThought/ModelResponseThought.tsx, templates/electron-typescript-react/src/App/components/InputRow/InputRow.css, templates/electron-typescript-react/src/App/components/MarkdownContent/MarkdownContent.tsx, templates/electron-typescript-react/src/App/components/MessageMarkdown/MessageMarkdown.css
* fix: uncaught exception
* fix(Electron template): non-latin text formatting
* docs: update DeepSeek
=> fix: uncaught exception

.vitepress/components/BlogEntry/BlogEntry.vue, .vitepress/config.ts
* docs: fix cover images
* docs: fix design glitch
=> docs: fix cover images

docs/guide/electron.md
=> docs: fix electron command

docs/guide/awesome.md, src/bindings/utils/getLlamaGpuTypes.ts, src/cli/recommendedModels.ts, src/evaluator/LlamaChatSession/LlamaChatSession.ts
* fix(`getLlamaGpuTypes`): edge case
* fix: remove prompt completion from the cached context window
* chore: update recommended models
* docs: update the awesome list
=> fix(`getLlamaGpuTypes`): edge case

test/modelDependent/llama3.2/promptCompletion.test.ts
=> test: fix a test

docs/guide/embedding.md, src/bindings/Llama.ts, src/bindings/types.ts, src/cli/commands/ChatCommand.ts, src/cli/commands/CompleteCommand.ts, src/cli/commands/InfillCommand.ts, test/modelDependent/bgeReranker/rank.test.ts
* fix: expose the numa setting on the `Llama` instance
* fix: add `--numa` flag to cli commands
* test: fix tests
=> fix(`Llama`): expose the `numa`

test/modelDependent/llama3.1/tokenBias.test.ts
* test: fix tests - `hello` can be made up of multiple tokens (`hell`, `lo`) and it too probable to appear in a greeting text
=> test: fix tests

src/bindings/utils/compileLLamaCpp.ts, src/evaluator/LlamaRankingContext.ts, src/gguf/insights/GgufInsights.ts, src/gguf/insights/GgufInsightsTokens.ts, src/gguf/types/GgufMetadataTypes.ts, src/index.ts, src/utils/parseModelUri.ts, src/utils/signalSleep.ts, src/utils/tokenizerUtils.ts, test/modelDependent/llama3.1/tokenPredictor.test.ts, test/standalone/cli/recommendedModels.test.ts
* feat: Qwen3 Reranker support
* fix: handle HuggingFace rate limit response
* fix: adapt to `llama.cpp` breaking changes
The new Qwen3 Reranker support only works with recent models converted with `llama.cpp` release [`b6578`](https://github.com/ggml-org/llama.cpp/releases/tag/b6578) or later.
Here are prequantized models you can use right away:
| Model                                                                          | URI                                        |    Size |
|:-------------------------------------------------------------------------------|:-------------------------------------------|--------:|
| [Qwen3 Reranker 0.6B](https://huggingface.co/giladgd/Qwen3-Reranker-0.6B-GGUF) | `hf:giladgd/Qwen3-Reranker-0.6B-GGUF:Q8_0` | 639.2MB |
| [Qwen3 Reranker …
=> feat: Qwen3 Reranker support
