withcatai/node-llama-cpp

- .releaserc.json
- src/AbortError.ts
- tsconfig.json
* Fix semantic release configuration to deploy a new version on `docs(README):` commits
* Add missing `stripInternal` configuration to `tsconfig.json`
> fix: configurations

- .config/typedoc.css
- .config/typedoc.json
- .github/workflows/build.yml
- .gitignore
- .releaserc.json
- README.md
- llama/addon.cpp
- package-lock.json
- package.json
- src/cli/commands/ChatCommand.ts
- src/llamaEvaluator/LlamaChatSession.ts
- src/llamaEvaluator/LlamaContext.ts
- src/llamaEvaluator/LlamaModel.ts
- src/utils/getBin.ts
* Added TSDoc documentation deployment to GitHub Pages
* Added GitHub environment support to the CI
> feat: add TSDoc

- README.md
Added a missing import in the `README.md` file
> docs(README): add missing import

- README.md
- package-lock.json
- package.json
* chore: remove unused dependencies
* docs(README): update `README.md`
> chore: remove unused dependencies

- README.md
docs(README): add a section explaining about Metal and CUDA support
> docs(README): add a section explaining about Metal and CUDA support

- package.json
- src/index.ts
- tsconfig.json
> fix: import

- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation-issue.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/prLint.yml
- .github/workflows/test.yml
* Added GitHub templates to new issues to make issues more complete, thus making them easier to solve
* Added PR title lint to make sure PR titles follow the convention `semantic-release` depends on
> feat: make contributions and support more efficient via GitHub templates

- src/index.ts
- src/llamaEvaluator/LlamaChatSession.ts
- src/llamaEvaluator/LlamaContext.ts
- src/llamaEvaluator/LlamaGrammar.ts
- src/llamaEvaluator/LlamaModel.ts
> feat: export class options types

- .config/typedoc.css
- README.md
- assets/logo.png
- assets/logo.roundEdges.png
- assets/star.please.png
- assets/star.please.roundEdges.png
- package.json
docs(README): improve `README.md` formatting and add images
> docs(README): improve `README.md` formatting and add images

- llama/addon.cpp
fix: adapt to `llama.cpp` interface change
> fix: adapt to `llama.cpp` interface change

- DEVELOPMENT.md
docs: fix typo in CONTRIBUTING.md
> docs: fix typo in CONTRIBUTING.md

- .config/typedoc.json
- .github/workflows/build.yml
- .gitignore
- README.md
- docs/CUDA.md
- src/utils/compileLLamaCpp.ts
docs: improve CUDA documentation
> docs: improve CUDA documentation

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- src/chatWrappers/FalconChatPromptWrapper.ts
- src/cli/commands/ChatCommand.ts
- src/index.ts
* feat: add `FalconChatPromptWrapper`
> feat: add `FalconChatPromptWrapper`

- .github/workflows/build.yml
- .github/workflows/test.yml
- README.md
* docs(README): add changelog link
* ci: add missing docs images
* ci: test docs compilation
> docs(README): add changelog link

- .vitepress/config.ts
- src/cli/commands/DownloadCommand.ts
* fix: add documentation website to Google Search
* fix: link to correct page edit url in documentation pages
* fix: typo
> fix: add documentation to Google Search

- llama/CMakeLists.txt
- src/cli/commands/ChatCommand.ts
- src/cli/commands/ClearCommand.ts
- src/utils/clearLlamaBuild.ts
- src/utils/clearTempFolder.ts
- src/utils/cmake.ts
- src/utils/compileLLamaCpp.ts
* fix: improve CUDA compilation
* feat: add `gpuLayers` option to the `chat` command
* fix: bugs
> fix: improve CUDA compilation

- .gitignore
- package-lock.json
- package.json
- src/utils/gbnfJson/utils/validateObjectAgainstGbnfSchema.ts
- test/standalone/llamaEvaluator/LlamaGrammar.test.ts
Improved JSON schema validation error messages
> fix: improve JSON schema validation error messages

- .releaserc.json
- docs/guide/index.md
- src/cli/cli.ts
- src/cli/commands/ChatCommand.ts
- src/config.ts
- src/utils/ReplHistory.ts
* feat: save and load history to `chat` command
* build: support patch bump of minor features
* fix: show correct cli command on Windows
> feat(minor): save and load history to `chat` command

- .vitepress/config.ts
- assets/social.poster.png
- docs/public/social.poster.jpg
* docs: add social poster
* improve social html head tags
> docs(README): add social poster

- .vitepress/config.ts
- README.md
- package.json
* Added roadmap links
* Improved `README.md`
> docs(README): add roadmap links, improve `README.md`

- package.json
* fix: add optional typescript peer dependency
Fixes #113
> fix: optional typescript peer dependency

- README.md
docs: update version 3 beta message
> docs(README): update version 3 beta message

- llama/addon.cpp
- src/cli/commands/ChatCommand.ts
- src/llamaEvaluator/LlamaContext.ts
- src/utils/getBin.ts
Add a --printTimings option to the CLI
> feat(minor): add `--printTimings` option to the `chat` CLI command

- src/cli/commands/ChatCommand.ts
- test/utils/prompts/longSystemPrompt.txt
* feat: add `--systemPromptFile` flag to the `chat` command
* feat: add `--promptFile` flag to the `chat` command
* feat: add `--batchSize` flag to the `chat` command
Based on #145 by @stewartoallen, adapted for the `beta` branch.
This is a new PR to merge to the `beta` branch instead of the `master` branch (supersedes the #147 PR)
> feat(minor): add more flags to the `chat` command

- .releaserc.ts
> fix: release config

- .github/workflows/build.yml
- src/cli/commands/OnPostInstallCommand.ts
* fix: build and postinstall bug
> fix: build and postinstall bug

- src/bindings/utils/cloneLlamaCppRepo.ts
> fix: clone from bundle

- README.md
* docs(README): update version 3 features
> docs(README): update version 3 features

- llama/addon.cpp
- package.json
- src/bindings/AddonTypes.ts
- src/cli/commands/ChatCommand.ts
- src/evaluator/LlamaChat/LlamaChat.ts
- src/evaluator/LlamaChatSession/LlamaChatSession.ts
- src/evaluator/LlamaContext/LlamaContext.ts
* feat: minP support
Resolve #119
> feat: minP support

- src/bindings/utils/resolveChatWrapperBasedOnWrapperTypeName.ts
- src/cli/commands/ChatCommand.ts
- src/index.ts
* feat: export `resolveChatWrapperBasedOnWrapperTypeName`
> feat: export `resolveChatWrapperBasedOnWrapperTypeName`

- llama/addon.cpp
* fix: adapt to `llama.cpp` breaking changes
> fix: adapt to `llama.cpp` breaking changes

- README.md
> fix: asset links

- .eslintrc.json
- src/bindings/AddonTypes.ts
- src/bindings/Llama.ts
- src/evaluator/LlamaChat/LlamaChat.ts
- src/evaluator/LlamaEmbeddingContext.ts
- src/evaluator/LlamaGrammar.ts
- src/evaluator/LlamaGrammarEvaluationState.ts
- src/types.ts
- src/utils/findCharacterRemovalCountToFitChatHistoryInContext.ts
- src/utils/gbnfJson/GbnfTerminal.ts
- src/utils/gbnfJson/terminals/GbnfArray.ts
- src/utils/gbnfJson/terminals/GbnfBoolean.ts
- src/utils/gbnfJson/terminals/GbnfBooleanValue.ts
- src/utils/gbnfJson/terminals/GbnfGrammar.ts
- src/utils/gbnfJson/terminals/GbnfNull.ts
- src/utils/gbnfJson/terminals/GbnfNumber.ts
- src/utils/gbnfJson/terminals/GbnfNumberValue.ts
- src/utils/gbnfJson/terminals/GbnfObjectMap.ts
- src/utils/gbnfJson/terminals/GbnfOr.ts
- src/utils/gbnfJson/terminals/GbnfString.ts
- src/utils/gbnfJson/terminals/GbnfStringValue.ts
- src/utils/gbnfJson/terminals/GbnfVerbatimText.ts
- src/utils/gbnfJson/terminals/GbnfWhitespace.ts
- src/utils/withOra.ts
* style: improve eslint config
> style: improve eslint config

- .github/workflows/build.yml
- llama/toolchains/win32.host-x64.target-arm64.cmake
* feat: Windows on Arm prebuilt binary
> feat: Windows on Arm prebuilt binary

- src/evaluator/LlamaModel.ts
- test/modelDependent/functionary/sanity.test.ts
* fix: create a context with no parameters
> fix: create a context with no parameters

- llama/addon.cpp
- src/bindings/AddonTypes.ts
- src/cli/commands/ChatCommand.ts
- src/cli/commands/CompleteCommand.ts
- src/cli/commands/InfillCommand.ts
- src/cli/utils/ConsoleInteraction.ts
- src/cli/utils/consolePromptQuestion.ts
- src/evaluator/LlamaChat/LlamaChat.ts
- src/evaluator/LlamaChatSession/LlamaChatSession.ts
- src/evaluator/LlamaCompletion.ts
- src/evaluator/LlamaContext/LlamaContext.ts
- src/evaluator/TokenBias.ts
- src/index.ts
- src/utils/isToken.ts
- src/utils/tokenizeInput.ts
- src/utils/withProgressLog.ts
* feat: token biases
* fix: bugs
Fixes #192
> feat: token biases

- llama/addon.cpp
* fix: adapt to `llama.cpp` changes
> fix: adapt to `llama.cpp` changes

- .github/workflows/build.yml
* fix: include templates in npm package
> fix: include templates in npm package

- scripts/packTemplates.ts
- templates/electron-typescript-react/package.json
> fix: templates bugs

- .github/workflows/build.yml
- src/bindings/utils/compileLLamaCpp.ts
- test/modelDependent/stableCode/stableCodeModelGpuLayersOptions.test.ts
* feat: compress CUDA prebuilt binaries
* feat: automatically solve more CUDA compilation errors
> feat: compress CUDA prebuilt binaries

- .github/workflows/build.yml
* fix: remove CUDA binary compression for now
> fix: remove CUDA binary compression for now

- .github/workflows/build.yml
- src/bindings/utils/getLinuxDistroInfo.ts
- src/cli/commands/ChatCommand.ts
- src/cli/commands/inspect/commands/InspectGpuCommand.ts
* fix: remove CUDA binary compression for Windows
* fix: improve `inspect gpu` command output
> fix: remove CUDA binary compression for Windows

- src/cli/commands/ChatCommand.ts
* fix: preload error on `chat` command
> fix: preload error on `chat` command

- .github/workflows/build.yml
- llama/addon.cpp
* fix: bump llama.cpp release used in prebuilt binaries
> fix: bump llama.cpp release used in prebuilt binaries

- src/evaluator/LlamaChat/LlamaChat.ts
- src/evaluator/LlamaChatSession/utils/LlamaChatSessionPromptCompletionEngine.ts
- src/evaluator/LlamaCompletion.ts
- src/utils/LlamaText.ts
- src/utils/TokenStreamRegulator.ts
- src/utils/pushAll.ts
- templates/electron-typescript-react/electron/state/llmState.ts
- test/modelDependent/llama3/chatSession.test.ts
- test/modelDependent/llama3/grammar.test.ts
* fix: long `LlamaText` tokenization
> fix: long `LlamaText` tokenization

- scripts/prepareStandalonePrebuiltBinaryModules.ts
> build: fix release job

- src/bindings/utils/compileLLamaCpp.ts
> fix: Windows build

- llama/CMakeLists.txt
* fix: Linux prebuilt binaries
> fix: Linux prebuilt binaries

- llama/addon.cpp
- src/chatWrappers/Llama3ChatWrapper.ts
- src/chatWrappers/generic/JinjaTemplateChatWrapper.ts
- src/cli/commands/ChatCommand.ts
- src/cli/commands/CompleteCommand.ts
- src/cli/commands/InfillCommand.ts
- src/cli/utils/interactivelyAskForModel.ts
- src/cli/utils/resolveCommandGgufPath.ts
- test/modelDependent/functionary/sanity.test.ts
* feat: flash attention in model selection
* fix: adapt to `llama.cpp` breaking changes
* fix: Llama 3 function calling
Fixes #267
> feat: flash attention in model selection

- llama/addon/addon.cpp
- package-lock.json
- package.json
- src/cli/recommendedModels.ts
- src/gguf/insights/GgufInsights.ts
- src/utils/createModelDownloader.ts
- templates/electron-typescript-react/src/App/App.tsx
* feat(model downloader): use `HF_TOKEN` when needed
* fix: update model recommendations
Fixes #275
> feat(model downloader): use `HF_TOKEN` when needed

- llama/addon/AddonContext.cpp
- llama/addon/AddonContext.h
- llama/addon/AddonGrammar.cpp
- llama/addon/AddonGrammar.h
- llama/addon/AddonGrammarEvaluationState.cpp
- llama/addon/AddonGrammarEvaluationState.h
- llama/addon/AddonModel.cpp
- llama/addon/AddonModel.h
- llama/addon/AddonModelLora.cpp
- llama/addon/AddonModelLora.h
- src/bindings/utils/compileLLamaCpp.ts
- src/evaluator/LlamaContext/LlamaContext.ts
* fix: CUDA context creation
* fix: detokenizer unpredictable text length
Fixes #283
Fixes #282
> fix: CUDA context creation

- src/evaluator/LlamaChat/LlamaChat.ts
- src/evaluator/LlamaCompletion.ts
* fix: unkown characters in generation streaming
Fixes #284
> fix: unkown characters in generation streaming

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build.yml
- .vitepress/config.ts
- CONTRIBUTING.md
- README.md
- package.json
- src/config.ts
* fix: documentation website URL
> fix: update documentation website URL

- .github/workflows/build.yml
> build: fix CI config

- .releaserc.ts
- package-lock.json
- package.json
- templates/electron-typescript-react/package.json
> build: fix release config

- .github/workflows/build.yml
- package-lock.json
- package.json
- scripts/patches/@semantic-release+npm+12.0.1.patch
> build: fix release bug

- .github/workflows/build.yml
- .github/workflows/test.yml
- .releaserc.ts
- package-lock.json
- package.json
- scripts/patches/vitepress+1.3.4.patch
- src/bindings/Llama.ts
- src/bindings/getLlama.ts
- src/cli/utils/printCommonInfoLines.ts
- src/evaluator/LlamaChatSession/utils/defineChatSessionFunction.ts
- src/evaluator/LlamaContext/LlamaContext.ts
- src/evaluator/LlamaContext/types.ts
- src/utils/ThreadsSplitter.ts
- test/standalone/utils/ThreadsSplitter.test.ts
* fix: no thread limit when using a GPU
* fix: improve `defineChatSessionFunction` types and docs
* fix: format numbers printed in the CLI
* fix: disable the browser's autocomplete in the docs search
> fix: no thread limit when using a GPU

- .vitepress/utils/parseCmakeListsTxtOptions.ts
- docs/guide/cmakeOptions.data.ts
- src/cli/recommendedModels.ts
- src/evaluator/LlamaChatSession/LlamaChatSession.ts
- templates/electron-typescript-react/src/App/components/ChatHistory/ChatHistory.css
- templates/electron-typescript-react/src/App/components/ChatHistory/ChatHistory.tsx
- templates/electron-typescript-react/src/App/components/ChatHistory/components/MessageCopyButton/MessageCopyButton.css
- templates/electron-typescript-react/src/App/components/ChatHistory/components/MessageCopyButton/MessageCopyButton.tsx
- templates/electron-typescript-react/src/icons/CheckIconSVG.tsx
- templates/electron-typescript-react/src/icons/CopyIconSVG.tsx
* feat: `resetChatHistory` function on a `LlamaChatSession`
* feat: copy model response in the example Electron app template
* chore: add `OLMoE` to recommended models
> feat: `resetChatHistory` function on a `LlamaChatSession`

- package-lock.json
- package.json
- src/cli/recommendedModels.ts
- src/evaluator/LlamaCompletion.ts
- src/utils/createModelDownloader.ts
- test/utils/modelFiles.ts
* fix: improve model downloader CI logs
* fix: `CodeGemma` adaptations
> fix: improve model downloader CI logs

- .github/workflows/build.yml
* build: release create-command package
> build: release create-command package

- .github/workflows/build.yml
* fix: release create-command package
> fix: release create-command package

- .github/workflows/build.yml
> build: deploy docs website

- .github/workflows/build.yml
> fix: deploy docs website

- .github/workflows/build.yml
- .github/workflows/test.yml
> docs: history

- .vitepress/config.ts
- docs/blog/v3.md
> build(docs): fix page time

- .vitepress/components/HomePage/HomePage.vue
> docs: home page fixes

- .github/workflows/build.yml
> build: fix CI

- .github/workflows/build.yml
- docs/guide/CUDA.md
- llama/CMakeLists.txt
- src/bindings/Llama.ts
- src/bindings/types.ts
- src/bindings/utils/compileLLamaCpp.ts
- src/bindings/utils/testBindingBinary.ts
- src/cli/commands/inspect/commands/InspectGpuCommand.ts
- src/evaluator/LlamaChatSession/LlamaChatSession.ts
* fix: prebuilt binaries CUDA 13 support
Fixes #493
> fix: CUDA 13 support

- .github/workflows/build.yml
- llama/addon/AddonContext.cpp
- llama/addon/globals/addonLog.h
- llama/gpuInfo/vulkan-gpu-info.cpp
- templates/electron-typescript-react/electron/state/llmState.ts
* fix(Vulkan): read external memory usage
* fix(Electron template): minor performance improvement
> fix(Vulkan): read external memory usage

- .github/workflows/build.yml
* build: update CI Vulkan SDK version
> build: update CI Vulkan SDK version
